# nav_msgs/Path includes field "poses", which is a vector of geometry_msgs/PoseStamped objects; 
# e.g., use this message to specify a coarse list of subgoals
nav_msgs/Path nav_path
---
#could use the response, e.g., to get back a finer-resolution, interpolated set of subgoals
nav_msgs/Path nav_path
